### ISSUE TITLE
TypeError: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by jonnieb007** [Netflix/repokid#223]
Hi 

I get the following error  when trying to update role cache

# repokid update_role_cache 1234567890 
Loaded config from /srv/dev/repokid-master/config.json
2019-07-01 14:11:18,169 INFO: Getting current role data for account 1234567890 (this may take a while for large accounts) [in /srv/dev/repokid-master/repokid/cli/repokid_cli.py:380]
INFO:repokid:Getting current role data for account 1234567890 (this may take a while for large accounts)
2019-07-01 14:11:19,554 INFO: Updating role data for account 1234567890 [in /srv/dev/repokid-master/repokid/cli/repokid_cli.py:392]
INFO:repokid:Updating role data for account 1234567890
100%|████████████████████████████████████████████████████████████| 28/28 [00:01<00:00, 23.74it/s]
2019-07-01 14:11:20,735 INFO: Finding inactive roles in account 1234567890 [in /srv/dev/repokid-master/repokid/cli/repokid_cli.py:399]
INFO:repokid:Finding inactive roles in account 1234567890
2019-07-01 14:11:20,748 INFO: Filtering roles [in /srv/dev/repokid-master/repokid/cli/repokid_cli.py:402]
INFO:repokid:Filtering roles
Traceback (most recent call last):
File "/bin/repokid", line 9, in <module>
load_entry_point('repokid==0.9.5', 'console_scripts', 'repokid')()
File "/srv/dev/repokid-master/repokid/cli/repokid_cli.py", line 1229, in main
return update_role_cache(account_number, dynamo_table, config, hooks)
File "/srv/dev/repokid-master/repokid/cli/repokid_cli.py", line 408, in update_role_cache
blocklist_filter_config['current_account'] = account_number
TypeError: 'NoneType' object does not support item assignment

Running on Python 2.7 as could not get it run on Python 3.6

**Comment by jonnieb007** [comment]
It seems to be an issue with Python 2.7 did update to latest 2.7 it worked

**Comment by jonnieb007** [comment]
It seems to be an issue with Python 2.7 did update to latest 2.7 it worked
