### ISSUE TITLE
"LoggerAdapter" object has no attribute "warn"

### ISSUE THREAD

**Issue by mfuellbier** [Netflix/repokid#238]
Hello,

after installing repokid as described in the README.md, I encounter the following error when invoking `repokid update_role_cache xxxx` where xxxx is an Account Number:
```
2019-09-11 09:17:54,039 INFO: Calculating repoable permissions and services for account xxxx [in /home/ec2-user/repokid/repokid/cli/repokid_cli.py:482]
Calculating repoable permissions and services for account xxxx
Traceback (most recent call last):
  File "/home/ec2-user/repokid/venv/bin/repokid", line 11, in <module>
    load_entry_point('repokid', 'console_scripts', 'repokid')()
  File "/home/ec2-user/repokid/repokid/cli/repokid_cli.py", line 1594, in main
    return update_role_cache(account_number, dynamo_table, config, hooks)
  File "/home/ec2-user/repokid/repokid/cli/repokid_cli.py", line 493, in update_role_cache
    batch_size,
  File "/home/ec2-user/repokid/repokid/utils/roledata.py", line 353, in _calculate_repo_scores
    hooks,
  File "/home/ec2-user/repokid/repokid/utils/roledata.py", line 581, in _get_repoable_permissions
    minimum_age,
  File "/home/ec2-user/repokid/repokid/utils/roledata.py", line 534, in _get_potentially_repoable_permissions
    LOGGER.warn("skipping {}".format(permission_name))
AttributeError: 'LoggerAdapter' object has no attribute 'warn'
```
I "fixed" this issue by replacing `LOGGER.warn` by `LOGGER.error` in `repokid/utils/roledata.py` in lines 528 and 534.

**Comment by mfuellbier** [comment]
Nevermind ... It works fine with python3 instead of python2.
