### ISSUE TITLE
repokid not finding modules attributes on release 0.14.0

### ISSUE THREAD

**Issue by rmtzcx** [Netflix/repokid#257]
Summary
========
Repokid is not running on version 0.14.0

it is failing with the following output:
```
Loaded config from /tmp/repokid/config.json
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/config.py", line 93, in _resolve
    found = getattr(found, n)
AttributeError: module 'repokid.utils' has no attribute 'logging'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/config.py", line 542, in configure
    formatters[name] = self.configure_formatter(
  File "/usr/lib64/python3.8/logging/config.py", line 674, in configure_formatter
    c = _resolve(cname)
  File "/usr/lib64/python3.8/logging/config.py", line 95, in _resolve
    __import__(used)
  File "/tmp/repokid/repokid/utils/logging.py", line 20, in <module>
    from repokid import LOGGER
ImportError: cannot import name 'LOGGER' from partially initialized module 'repokid' (most likely due to a circular import) (/tmp/repokid/repokid/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/repokid/venv/bin/repokid", line 11, in <module>
    load_entry_point('repokid', 'console_scripts', 'repokid')()
  File "/tmp/repokid/venv/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/tmp/repokid/venv/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/tmp/repokid/venv/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/tmp/repokid/venv/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/tmp/repokid/repokid/__init__.py", line 119, in <module>
    LOGGER = init_logging()
  File "/tmp/repokid/repokid/__init__.py", line 66, in init_logging
    logging.config.dictConfig(CONFIG["logging"])
  File "/usr/lib64/python3.8/logging/config.py", line 808, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib64/python3.8/logging/config.py", line 545, in configure
    raise ValueError('Unable to configure '
ValueError: Unable to configure formatter 'json'
```

How to reproduce
==============
I followed the instructions below in Fedora 32/Python 3.8.3 and AmazonLinux2/Python 3.7.6

**Clone code**
```
git clone https://github.com/Netflix/repokid.git
```

**Create virtual environment and activate it**
```
cd repokid
python3 -m venv venv
source venv/bin/activate
```

**Install and configure repokid**
```
pip install -e .
repokid config config.json
```

**Repokid is not even able to show the version**
```
repokid --version
```

Confirm previous release is working
===========================
**Previous version is 0.13.0 and just one commit back**
```
git log --oneline
```

Output from command above:
```
4ba6d54 (HEAD -> master, tag: 0.14.0, origin/master, origin/HEAD) Refactor CLI calls into repokid.commands module (#255)
7852827 (tag: 0.13.0) Unpin Marshmallow requirement (#254)
```

**Checkout former commit**
```
git checkout 0.14.0~
```

**Downgrade repokid**
```
pip install -e .
```

**Confirm it is able to run**
```
repokid --version
```

Output from command above:
```
Loaded config from /tmp/repokid/config.json
Repokid 0.13.0
```

**Comment by patricksanders** [comment]
Hey @rmtzcx, thanks for reporting. Would it be possible for you to share your config? I'm not getting this failure with a clean install using my test config.

**Comment by rmtzcx** [comment]
You don't even need a 'valid' config. It fails in the same way with a 'valid' or template config with `repo config config.json`

**Comment by patricksanders** [comment]
Yep, you're right! Looking into this now.
