### ISSUE TITLE
TypeError: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by kwentland** [Netflix/repokid#284]
After update I am receiving the error "TypeError: can't compare offset-naive and offset-aware datetimes" when running "repokid update_role_cache <AWS ACCOUNT NUMBER>"

Output from command is below:

Traceback (most recent call last):
  File "/root/aardvark/env/bin/repokid", line 11, in <module>
    load_entry_point('repokid', 'console_scripts', 'repokid')()
  File "/root/aardvark/env/lib64/python3.7/site-packages/click-8.0.0rc1-py3.7.egg/click/core.py", line 1041, in __call__
    return self.main(*args, **kwargs)
  File "/root/aardvark/env/lib64/python3.7/site-packages/click-8.0.0rc1-py3.7.egg/click/core.py", line 971, in main
    rv = self.invoke(ctx)
  File "/root/aardvark/env/lib64/python3.7/site-packages/click-8.0.0rc1-py3.7.egg/click/core.py", line 1563, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/aardvark/env/lib64/python3.7/site-packages/click-8.0.0rc1-py3.7.egg/click/core.py", line 1309, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/aardvark/env/lib64/python3.7/site-packages/click-8.0.0rc1-py3.7.egg/click/core.py", line 715, in invoke
    return callback(*args, **kwargs)
  File "/root/aardvark/env/lib64/python3.7/site-packages/click-8.0.0rc1-py3.7.egg/click/decorators.py", line 23, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/aardvark/repokid/repokid/cli/repokid_cli.py", line 199, in update_role_cache
    _update_role_cache(account_number, config, hooks)
  File "/root/aardvark/repokid/repokid/commands/role_cache.py", line 76, in _update_role_cache
    filtered_list = plugin.apply(roles)
  File "/root/aardvark/repokid/repokid/filters/age/__init__.py", line 40, in apply
    elif role.create_date > now - ago:
TypeError: can't compare offset-naive and offset-aware datetimes

**Comment by patricksanders** [comment]
Hi @kwentland, thanks for the report. What version of Repokid are you running?

**Comment by kwentland** [comment]
I am using the latest that was released yesterday.


*Kevin Wentland*

Senior Cybersecurity Engineer

1-800-760-6915 main

1-412-879-0308 mobile

***@***.***

LinkedIn <https://www.linkedin.com/in/kevin-wentland-473251145>
This correspondence is from HealthPlanCRM, LLC, d/b/a Cavulus. Any
unauthorized or improper disclosure, copying, distribution, or use of the
contents of this message is prohibited. The information contained in this
message is intended only for the personal and confidential use of the
recipient(s) named above. If you have received this message in error,
please notify the sender immediately and delete the original message.

**Comment by patricksanders** [comment]
Thanks, I was able to reproduce and implement a fix in #285. Will merge and cut a new release shortly.

**Comment by patricksanders** [comment]
Also, I edited your last comment to remove the contact info that was in your email signature

**Comment by patricksanders** [comment]
Merged! Created release v0.18.6 with the fix. Thanks!
