### ISSUE TITLE
When running update_role_cache - cannot import name 'TableExistsWaiter' from 'mypy_boto3_dynamodb.paginator' 

### ISSUE THREAD

**Issue by kwentland** [Netflix/repokid#287]
Loaded config from /root/aardvark/repokid/config.json
Traceback (most recent call last):
  File "/root/aardvark/env/bin/repokid", line 11, in <module>
    load_entry_point('repokid', 'console_scripts', 'repokid')()
  File "/root/aardvark/env/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/root/aardvark/env/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/root/aardvark/env/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/root/aardvark/env/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/aardvark/repokid/repokid/cli/repokid_cli.py", line 24, in <module>
    from repokid.commands.repo import _repo_all_roles
  File "/root/aardvark/repokid/repokid/commands/repo.py", line 31, in <module>
    from repokid.role import Role
  File "/root/aardvark/repokid/repokid/role.py", line 55, in <module>
    from repokid.utils.dynamo import get_role_by_arn
  File "/root/aardvark/repokid/repokid/utils/dynamo.py", line 15, in <module>
    from mypy_boto3_dynamodb.service_resource import Table
  File "/root/aardvark/env/lib64/python3.7/site-packages/mypy_boto3_dynamodb/__init__.py", line 40, in <module>
    from .client import DynamoDBClient
  File "/root/aardvark/env/lib64/python3.7/site-packages/mypy_boto3_dynamodb/client.py", line 34, in <module>
    from .paginator import (
ImportError: cannot import name 'TableExistsWaiter' from 'mypy_boto3_dynamodb.paginator' (/root/aardvark/env/lib64/python3.7/site-packages/mypy_boto3_dynamodb/paginator.py)

**Comment by patricksanders** [comment]
Hey @kwentland, I just started seeing this error as well. Tracking it down now. Likely has to do with recent dependency upgrades.

**Comment by patricksanders** [comment]
This looks like vemel/mypy_boto3_builder#75. Will roll back to the previous version.

**Comment by patricksanders** [comment]
Alright, downgraded and released in `0.19.2`. Give that a shot and let me know if it works for you.

**Comment by patricksanders** [comment]
You may have to explicitly install the older version of the `mypy-boto3-*` packages:

```bash
pip install boto3==1.17.71 mypy-boto3-dynamdb==1.17.71 mypy-boto3-iam==1.17.71 mypy-boto3-sns==1.17.71 mypy-boto3-sqs==1.17.71 
```

**Comment by kwentland** [comment]
New install and explicitly installed the older versions get the following:
Traceback (most recent call last):
  File "/root/aardvark/env/bin/repokid", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/root/aardvark/env/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 3261, in <module>
    @_call_aside
  File "/root/aardvark/env/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 3245, in _call_aside
    f(*args, **kwargs)
  File "/root/aardvark/env/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 3274, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/root/aardvark/env/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/aardvark/env/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/aardvark/env/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'mypy-boto3-sqs==1.17.72; extra == "sqs"' distribution was not found and is required by boto3-stubs

**Comment by kwentland** [comment]
Now getting this error:

pkg_resources.DistributionNotFound: The 'mypy-boto3-sns==1.17.72; extra == "sns"' distribution was not found and is required by boto3-stubs

**Comment by patricksanders** [comment]
Yeah, looks like `boto3-stubs` needs to be pinned as well. I just opened #288 which should fix this issue without having to manually install the stub packages.

**Comment by patricksanders** [comment]
`v0.19.3` should be up on PyPI momentarily, let me know if that fixes the issue for you.

**Comment by kwentland** [comment]
Yep, all is working again!  Thanks!
