### ISSUE TITLE
repokid.filters.optout.OptOutFilter cause IndexError: list index out of range

### ISSUE THREAD

**Issue by Mortinke** [Netflix/repokid#38]
Environment:
```
(venv) ubuntu@********:/usr/local/src/repokid$ python --version
Python 2.7.12
(venv) ubuntu@********:/usr/local/src/repokid$ cat /etc/issue
Ubuntu 16.04.2 LTS \n \l
(venv) ubuntu@********:/usr/local/src/repokid$ git show
commit 40992a0e623ad13c883b171feace68476cd8ec5e
Author: Travis McPeak <tmcpeak@netflix.com>
Date:   Wed Aug 2 14:47:40 2017 -0700

    Last commit missed a bug, this fixes it

diff --git a/repokid/utils/dynamo.py b/repokid/utils/dynamo.py
index 4d5985a..ea93223 100644
--- a/repokid/utils/dynamo.py
+++ b/repokid/utils/dynamo.py
@@ -120,7 +120,7 @@ def find_role_in_cache(dynamo_table, account_number, role_name):
         string: RoleID for active role with name in given account, else None
     """
     for roleID in role_ids_for_account(dynamo_table, account_number):
-        role_data = get_role_data(dynamo_table, roleID, fields=['RoleName', 'Active'])
+        role_data = get_role_data(dynamo_table, roleID, fields=['RoleName', 'Active', 'RoleId'])
         if role_data['RoleName'].lower() == role_name.lower() and role_data['Active']:
             return role_data['RoleId']
```

I always get the error message "IndexError: list index out of range" when the filter "repokid.filters.optout.OptOutFilter" is activated:
```
(venv) ubuntu@********:/usr/local/src/repokid$ repokid update_role_cache <account_id>
Loaded config from /usr/local/src/repokid/config.json
2017-08-08 03:59:26,027 INFO: Updating role data for account <account_id> [in /usr/local/src/repokid/repokid/cli/repokid_cli.py:265]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23/23 [00:06<00:00,  3.89it/s]
2017-08-08 03:59:32,731 INFO: Finding inactive accounts [in /usr/local/src/repokid/repokid/cli/repokid_cli.py:272]
2017-08-08 03:59:32,744 INFO: Filtering roles [in /usr/local/src/repokid/repokid/cli/repokid_cli.py:275]
2017-08-08 03:59:32,744 INFO: Loaded plugin repokid.filters.age:AgeFilter [in /usr/local/src/repokid/repokid/cli/repokid_cli.py:222]
2017-08-08 03:59:32,745 INFO: Loaded plugin repokid.filters.lambda:LambdaFilter [in /usr/local/src/repokid/repokid/cli/repokid_cli.py:222]
2017-08-08 03:59:32,745 INFO: Loaded plugin repokid.filters.blacklist:BlacklistFilter [in /usr/local/src/repokid/repokid/cli/repokid_cli.py:222]
Traceback (most recent call last):
  File "/usr/local/src/repokid/venv/bin/repokid", line 11, in <module>
    load_entry_point('repokid', 'console_scripts', 'repokid')()
  File "/usr/local/src/repokid/repokid/cli/repokid_cli.py", line 770, in main
    return update_role_cache(account_number, dynamo_table, config)
  File "/usr/local/src/repokid/repokid/cli/repokid_cli.py", line 282, in update_role_cache
    plugin_name = plugin_path.split(':')[1]
IndexError: list index out of range
```

If I remove the "repokid.filters.optout.OptOutFilter" from the active_filters, everything works well.
```
    "active_filters": [
        "repokid.filters.age:AgeFilter",
        "repokid.filters.lambda:LambdaFilter",
        "repokid.filters.blacklist:BlacklistFilter",
        "repokid.filters.optout.OptOutFilter"
    ],
```

**Comment by mcpeak** [comment]
Bah, `repokid.filters.optout.OptOutFilter` should be `repokid.filters.optout:OptOutFilter`.  I've pushed a fix.  Thanks for reporting!

**Comment by Mortinke** [comment]
Thanks for the fix, it works now.
