### ISSUE TITLE
KeyError: 'DisqualifiedBy'

### ISSUE THREAD

**Issue by henaege** [Netflix/repokid#60]
When running repokid update_role_cache <Account Number>, we get the following error:

Traceback (most recent call last):
  File "/home/ec2-user/.virtualenvs/repokid/bin/repokid", line 11, in <module>
    load_entry_point('repokid', 'console_scripts', 'repokid')()
  File "/home/ec2-user/repokid/repokid/cli/repokid_cli.py", line 953, in main
    return update_role_cache(account_number, dynamo_table, config, hooks)
  File "/home/ec2-user/repokid/repokid/cli/repokid_cli.py", line 408, in update_role_cache
    roledata.update_role_data(dynamo_table, account_number, role, current_policies)
  File "/home/ec2-user/repokid/repokid/utils/roledata.py", line 197, in update_role_data
    current_role_data.pop('DisqualifiedBy')
KeyError: 'DisqualifiedBy'

Where should we look to start troubleshooting?

**Comment by mcpeak** [comment]
Hi @henaege, I think you've found a bug - that should be wrapped in a try in case the field doesn't exist yet.  PR coming.
